### ISSUE TITLE
Waffle.io Shutting down

### ISSUE THREAD

**Issue by matthewbadeau** [mozilla-lockwise/mozilla-lockwise.github.io#112]
[Waffle.io is shutting down](https://waffle.io/closing-its-doors) on May 16th, 2019. The following projects are using Waffle and will need to migrate to Github Projects, Zenhub or another platform for project management:
https://github.com/mozilla-lockbox/lockbox-addon
https://github.com/mozilla-lockbox/lockbox-ios
https://github.com/mozilla-lockbox/lockbox-android
https://github.com/mozilla-lockbox/lockbox-extension

 I have no affiliation with Waffle. I just noticed the notification when I found the project and was looking through the issues. Please let me know if I'm posting this issue to the wrong repository.

**Comment by devinreams** [comment]
Thanks @matthewbadeau 😁

**Comment by devinreams** [comment]
Consolidated Mobile Project:
https://github.com/orgs/mozilla-lockwise/projects/7

Addon project:
https://github.com/mozilla-lockwise/lockwise-addon/projects/1
