### ISSUE TITLE
Assemble possible error conditions into a single starting place

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockwise/mozilla-lockwise.github.io#34]
There are a number of places that things can go wrong.  Some of those conditions are documented in issues and existing architecture documents, without clear guidance or approach for handling, reporting, and mitigating.

To aid in a holistic guide for error handling and reporting, the current and foreseen error conditions are to be assembled and documented.

**Comment by devinreams** [comment]
Related work here: https://github.com/mozilla-lockbox/lockbox-extension/issues/631
