### ISSUE TITLE
Google Form Requires Login

### ISSUE THREAD

**Issue by daniel-barrows** [mozilla-lockwise/mozilla-lockwise.github.io#92]
The [Android app notification form](https://docs.google.com/forms/d/e/1FAIpQLSdT89hayWrOuKEp8sryNEcdkfZZALie_6flk_RDXVkV_56g2A/viewform) requires that you be logged in to Google in order to fill it out. It shouldn't.

The form is linked to from https://lockbox.firefox.com/faq.html

**Comment by devinreams** [comment]
Thanks for the feedback. The app is now live, so the form is no longer referenced or necessary.

https://play.google.com/store/apps/details?id=mozilla.lockbox
