### ISSUE TITLE
Remove or Update Outdated Documentation

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockwise/mozilla-lockwise.github.io#94]
Some of the documentation in this repo (particularly in `/architecture`) is very outdated.  Yet it's continued publication is being used as evidence in other architectural discussions.  It needs to be removed and/or replaced to reflect the current architecture.

**Comment by devinreams** [comment]
I propose removing it entirely for now, we can always recover anything that was useful but would rather not mislead: #115
